### ISSUE TITLE
DateRangePicker | Popup re-opens when trying to use it as a controlled component

### ISSUE THREAD

**Issue by ypahalajani** [innovaccer/design-system#1176]
## Description

When trying to use this as a controlled component, the popup re-opens when a new range is selected. 

### Steps to reproduce

[Codesandbox link](https://codesandbox.io/s/date-range-picker-bug-r8jr6l?file=/index.js)

### Expected result

After a new range is selected, the daterange picker popup should close and remain closed until interacted with again.

### Actual result

After a new range is selected, the daterange picker popup closes and reopens.

**Comment by innosatyam** [comment]
Fixed #1180
