### ISSUE TITLE
MetricInput and TextArea Components are not working properly in Firefox

### ISSUE THREAD

**Issue by souvik1000** [innovaccer/design-system#1404]
## Description

1. The MetricInput component is not working properly. On Chrome, It's working fine, But for Firefox it's not working properly. Which you can see on the DS storybook itself.
Inside Firefox, it's coming with two selector when I'm providing a suffix and due to that min-max functionality is not working properly. [[Link to check in Firefox](https://mds.innovaccer.com/?path=/docs/components-metricinput-with-suffix--with-suffix)] 

2. Inside Firefox, I am not able to resize using the textarea-resizing button of the TextArea component. [[Link to check in Firefox](https://mds.innovaccer.com/?path=/docs/components-textarea-textarea-with-caption--textarea-with-caption)]

### Steps to reproduce

1. **MetricInput**: 
When I'm using the MetricInput component with the suffix inside Firefox, two handlers are coming on and before the provided suffix. If I'm providing min or max value on it, then also it's not working on it.

2. **TextArea**:
When I'm using the Textarea component inside Firefox, it's not providing the resize-textarea section to us.

### Expected result

1. **MetricInput**:
![expected-metricInput](https://user-images.githubusercontent.com/60292800/182543227-7c7fac46-6863-4b99-9ba7-81ec210d5d21.png)

3. **Textarea**:
![expected-textarea](https://user-images.githubusercontent.com/60292800/182543293-64a080df-a244-448e-9115-ea28689fc0c1.png)

### Actual result

1. **MetricInput**:
![result-metricInput](https://user-images.githubusercontent.com/60292800/182543494-aba019ec-095c-4cf4-843a-d09879e6e407.png)

2. **Textarea**:
![result-textarea](https://user-images.githubusercontent.com/60292800/182543535-ee29368f-415a-4f8e-8200-bec1c8fde8c2.png)

**Comment by youngheart12** [comment]
Here is separate PR for input metric  : https://github.com/innovaccer/design-system/pull/2037

**Comment by youngheart12** [comment]
PR 2 for Textarea : https://github.com/innovaccer/design-system/pull/2038

@anuradha9712
