### ISSUE TITLE
In dropdown, selected value is calling onChange when user clicked on the selected value

### ISSUE THREAD

**Issue by atifzaidi92** [innovaccer/design-system#1557]
## Description

Describe the issue that you're seeing.
OnChange is called on clicking of the selected value in the dropdown
### Steps to reproduce
1. open the dropdown
2. select some value
3. open again the dropdown
4. select same value again
5. onChange is fired

Clear steps describing how to reproduce the issue.

### Expected result

What should happen?
if i clicked on the selected value, it should not call the onchange
### Actual result

What happened.
onchange is fired

**Comment by veekays** [comment]
This issue has been resolved.
PR link:- https://github.com/innovaccer/design-system/pull/1563
