### ISSUE TITLE
if user clicked same value multiple times in single selection dropdown, onChange is calling multiple times

### ISSUE THREAD

**Issue by atifzaidi92** [innovaccer/design-system#1559]
## Description

Describe the issue that you're seeing.
onchange is calling multiple times if user click multiple times same value
### Steps to reproduce

Clear steps describing how to reproduce the issue.
1. open the dropdown
2. click multiple times same value
3. onchange is calling multiple times

### Expected result

What should happen?
should not call onChange if user click multiple times same value
### Actual result

What happened.
multiple onchange called for same value

**Comment by veekays** [comment]
This issue has been resolved.
PR link:- https://github.com/innovaccer/design-system/pull/1563
