### ISSUE TITLE
there is some space between dropdown and dropdown popover

### ISSUE THREAD

**Issue by atifzaidi92** [innovaccer/design-system#1561]
## Description

Describe the issue that you're seeing.
if dropdown popover is opening top of the dropdown and there is no data or less data than we are seeing some space between dropdown and the dropdown popover.

### Steps to reproduce

Clear steps describing how to reproduce the issue.
1. use a dropdown with dropdown option on the top
2. search no result value or less data value
3. after the search result we can see some space between dropdown and the dropdown option's popover

### Expected result

What should happen?
no space between dropdown and dropdown options

### Actual result

What happened.
there is some space between dropdown and dropdown options

<img width="1131" alt="Screenshot 2022-11-15 at 4 46 18 PM" src="https://user-images.githubusercontent.com/54103064/201906479-e1b12ebd-b380-4c59-bfcf-53a67e248297.png">

**Comment by AnaghSharma** [comment]
@shubhamahuja1399 Here it is.

**Comment by veekays** [comment]
This issue has been resolved.
The PR link:- https://github.com/innovaccer/design-system/pull/1607
