### ISSUE TITLE
onSearch should not trigger after changing the state of error prop in case of a sync table

### ISSUE THREAD

**Issue by Sabahatnoorkhan** [innovaccer/design-system#1741]
**Description**

- When I am changing the the value of error prop in the sync table then Onsearch is also triggering

**Steps to reproduce**

`const [dataCount, setDataCount] = React.useState(data.length);
        <Table
            onSearch={(rawData, searchString) => {
              console.log('onSearch triggered')
              const filtered = rawData.filter(row =>
                row.name
                  .toLocaleLowerCase()
                  .includes(searchString.toLocaleLowerCase()),
              );
              setDataCount(filtered.length);
              return filtered;
            }}
            headerOptions={{
              withSearch: true,
            }}
            error={dataCount === 0}
          />`

1. Define a state dataCount
2. console 'onSearch triggered' inside onSearch and then set the value of filtered count setDataCount(Filtered.length)
3. error prop should depend on DataCount as shown in the above code (error = {dataCount===0}

**Expected result**

- 'onSearch triggered' should be printed on the console only once in case of filteredCount===0

**Actual result**

- 'onSearch triggered' is printing twice on the console  in case of filteredCount===0

**Comment by anuradha9712** [comment]
This issue has been resolved in this PR #1759
