### ISSUE TITLE
z-index for backdrop is not working as expected 

### ISSUE THREAD

**Issue by atifzaidi92** [innovaccer/design-system#1776]
## Description
if we opened a side sheet or modal or dropdown list and use backdrop, backdrop z-index is less than all three components z-index

### Steps to reproduce

Clear steps describing how to reproduce the issue.
use a dropdown
open the dropdown popover(option list)
add backdrop after opening the option list

### Expected result
latest backdrop z-index should be maximum based on rendering order

### Actual result

dropdown z-index is less than all three components

**Comment by youngheart12** [comment]
@atifzaidi92 Can you please attach a screenshot or a video for the same to better understand the problem.
