### ISSUE TITLE
EditableChipInput's characters is going out of field.

### ISSUE THREAD

**Issue by Chandan9898Kumar** [innovaccer/design-system#2061]
description of the bug :

EditableChipInput field have fixed width and after typing something which having more characters ( ex- 30 , 40) then chip field is going out of the input filed width.

1. Go to design system
2. Click on EditableChipInput all button
3. type anything which is having lots of characters and press enter.

Expected behavior :
chip width should be fixed.

Solution :
Fixed the chip width and use hover (when user hover over the chip box then show entire text)

**Comment by griseduardo** [comment]
Hello, I would like work in this issue, can you assign me?

**Comment by griseduardo** [comment]
Hello @anuradha9712 , I opened the PR here: https://github.com/innovaccer/design-system/pull/2393
