### ISSUE TITLE
Need a prop to show navItems in expanded state if it has submenu and it's submenu is not in active state in VerticalNav.

### ISSUE THREAD

**Issue by Sabahatnoorkhan** [innovaccer/design-system#2068]
## Summary
In VerticalNav, we need to show navItems in an expanded state, i.e., Its submenu should be visible even if it's not active.

### Basic example
When we come to the Patient page, the Care management submenu like Goals, Assessments, etc should be visible(expanded) even if none of the care management submenu is in active state.

### Motivation
Right now we are using a custom vertical nav and we show Care management in an expanded state so as to maintain consistency and reduce user clicks we want to maintain this functionality when we migrate to the DS vertical nav

**Comment by anuradha9712** [comment]
This issue has been fixed in this [PR](https://github.com/innovaccer/design-system/pull/2074)
