### ISSUE TITLE
Table: Cannot specify min-width and width in percentage for cell

### ISSUE THREAD

**Issue by amitb01** [innovaccer/design-system#230]
### Description
For responsive layouts, need the option to specify cell width in percentage and also give min-width. As of now, cell width can only be given in pixels values. 

### Expected result
Cells can be better adapted to the available table width. 

### Actual result

**Comment by aditya-kumawat** [comment]
Will add support to add min-width/max-width of a column.

**Comment by satyamyadav** [comment]
Support for min-width and max-width is added (#248 ), will take percentage width in next release.
