### ISSUE TITLE
Search Input: search clear button is not visible

### ISSUE THREAD

**Issue by amitb01** [innovaccer/design-system#231]
### Description
While using the SearchInput, the search clear btn is not visible after typing text in the input box. The input was not disabled and I also provided the onClear prop.

### Steps to reproduce
Provide the onClear prop to Search Input. Enter text into input field. 

### Expected result
After entering some text into the input field and defining the onClear callback, the input clear btn should be made visible. 

### Actual result
After entering some text into the input field and defining the onClear callback, the input clear btn is NOT visible.

**Comment by aditya-kumawat** [comment]
Thanks for mentioning this out. I will update the docPage for the same.
Clear button is only visible if you are using Controlled Input, i.e. if you pass value along with onClear callback.
<img width="1002" alt="Screenshot 2020-07-20 at 11 44 01 AM" src="https://user-images.githubusercontent.com/12715487/87905576-89836080-ca7e-11ea-8e72-149661c1f565.png">

**Comment by satyamyadav** [comment]
Resolved in #266
