### ISSUE TITLE
Docs Site: Switching components keeps the 'Code' tab selected, but displays content from the 'Usage' tab instead

### ISSUE THREAD

**Issue by anuradha9712** [innovaccer/design-system#2366]
## Description

On the [docs site](https://design.innovaccer.com/components/avatar/code/), if the user switch to `Code` tab for any component and then navigate to any other component, the `Code` tab remains in selected state but the content shown is of `Usage` tab.

https://github.com/user-attachments/assets/5c529d6f-b1ca-4a42-9dd7-3b1ebbfc47a7

### Expected result

Tab should highlight properly based on the current content of the page.

### Steps to fix the issue

- Fork and clone this repository
- First checkout to `develop` branch, and from that create a new branch
- Switch current directory to **docs** using command  ```cd docs```
- Install dependencies using ```npm install```
- Start development server using ```npm run dev```
- Check the issue on your local environment on localhost:8000
- Refer to [this](https://github.com/innovaccer/design-system/blob/master/docs/src/components/Container/ComponentsContainer.js)

**Comment by pranjalee30** [comment]
Hey @anuradha9712 mam, Can you please assign this to me?

**Comment by youngheart12** [comment]
@anuradha9712 Please review
