### ISSUE TITLE
Docs Site: When navigating to any page, the corresponding item in the left vertical navigation is not highlighted.

### ISSUE THREAD

**Issue by anuradha9712** [innovaccer/design-system#2367]
## Description

On the [docs site](https://design.innovaccer.com/foundations/principles/), When navigating to any page, the corresponding item in the left vertical navigation is not highlighted but it gets highlighted when anyone clicks on it.

https://github.com/user-attachments/assets/e0262468-51a9-44dd-9c91-04b508a0f912

### Expected result

Corresponding item in the left vertical navigation should be highlighted based on the current active page.

### Steps to fix the issue

- Fork and clone this repository
- First checkout to `develop` branch, and from that create a new branch
- Switch current directory to **docs** using command  ```cd docs```
- Install dependencies using ```npm install```
- Start development server using ```npm run dev```
- Check the issue on your local environment on localhost:8000
- Refer to [this](https://github.com/innovaccer/design-system/blob/master/docs/src/components/LeftNav/LeftNav.js)

**Comment by Samyak-Waghmare** [comment]
@anuradha9712 hey, can you assign this issue to me?

**Comment by Ab2602** [comment]
Hello @anuradha9712 ,
I am interested to work on this issue.

Kindly assign me this

**Comment by youngheart12** [comment]
@anuradha9712 Please assign this to me , the PR for the same has been raised
