### ISSUE TITLE
Button: update story of Button component and replace Dropdown with Menu component

### ISSUE THREAD

**Issue by anuradha9712** [innovaccer/design-system#2380]
## Summary

In [Split Button](https://mds.innovaccer.com/?path=/docs/components-button-button-split-button--split-button) story, Replace the Dropdown component with the new [Menu](https://mds.innovaccer.com/?path=/docs/components-menu-all--all) component.

![image](https://github.com/user-attachments/assets/d63ed8ec-a5bc-451e-a703-cb187b593854)

### Motivation

We are now deprecating the Dropdown component and need to update all the examples with the new Menu component.

## Steps to resolve this issue

- Fork and clone this repository
- First checkout to `develop` branch, and from that create a new branch
- Install dependencies using ```npm install```
- Start development server using ```npm run dev```
- Check the issue on your local environment on localhost:5000
- Refer to [this](https://github.com/innovaccer/design-system/blob/master/core/components/atoms/button/__stories__/SplitButton.story.jsx)

**Comment by griseduardo** [comment]
Hello, I would like work in this issue, can you assign me?

**Comment by griseduardo** [comment]
Hello @anuradha9712 , I opened the PR here: https://github.com/innovaccer/design-system/pull/2399
