### ISSUE TITLE
HelpText: update story of HelpText component and replace Dropdown with Select component

### ISSUE THREAD

**Issue by anuradha9712** [innovaccer/design-system#2381]
## Summary

In [HelpText](https://mds.innovaccer.com/?path=/docs/components-helptext-all--all) story, Replace the Dropdown component with the new [Select](https://mds.innovaccer.com/?path=/docs/components-select-all--all) component. 

![image](https://github.com/user-attachments/assets/3555e4f2-9c93-4782-bf55-eb9a0624a1de)

### Motivation

We are now deprecating the [Dropdown](https://mds.innovaccer.com/?path=/docs/components-dropdown-deprecated-all--all) component and need to update all the examples with the new [Select](https://mds.innovaccer.com/?path=/docs/components-select-all--all) component.

## Steps to resolve this issue

- Fork and clone this repository
- First checkout to `develop` branch, and from that create a new branch
- Install dependencies using npm install
- Start development server using npm run dev
- Check the issue on your local environment on localhost:5000
- Refer to [this](https://github.com/innovaccer/design-system/blob/master/core/components/atoms/helpText/__stories__/index.story.jsx)

**Comment by dead8309** [comment]
I would like to work on this one

**Comment by dead8309** [comment]
@anuradha9712 looks like the issue is still not closed yet
