### ISSUE TITLE
Modal: update story of Modal component and replace Dropdown with Select component

### ISSUE THREAD

**Issue by anuradha9712** [innovaccer/design-system#2382]
## Summary

In [Modal- Input Modal](https://mds.innovaccer.com/?path=/docs/components-modal-modal-input-modals--input-modals) story, Replace the Dropdown component with the new [Select](https://mds.innovaccer.com/?path=/docs/components-select-all--all) component.

![image](https://github.com/user-attachments/assets/7b22a521-8944-45c6-ae82-3860845cad37)

### Motivation

We are now deprecating the [Dropdown](https://mds.innovaccer.com/?path=/docs/components-dropdown-deprecated-all--all) component and need to update all the examples with the new [Select](https://mds.innovaccer.com/?path=/docs/components-select-all--all) component.

## Steps to resolve this issue

- Fork and clone this repository
- First checkout to `develop` branch, and from that create a new branch
- Install dependencies using npm install
- Start development server using npm run dev
- Check the issue on your local environment on localhost:5000
- Refer to [this](https://github.com/innovaccer/design-system/blob/master/core/components/molecules/modal/__stories__/Input.story.jsx)

**Comment by swarupn17** [comment]
Hey @anuradha9712 I can do this task. Please can you assign it to me.
Thanks!

**Comment by Buddha-11** [comment]
@anuradha9712  please assign this task to me as there has not been any progress

**Comment by Kritik-Kapoor** [comment]
@anuradha9712  I've created a PR that solves this issue, would appreciate a review.
