### ISSUE TITLE
Popover: update story of Popover component and replace Dropdown with Select component

### ISSUE THREAD

**Issue by anuradha9712** [innovaccer/design-system#2383]
## Summary

In [Popover](https://mds.innovaccer.com/?path=/docs/components-popover-layering--layering) story, Replace the Dropdown component with the new [Select](https://mds.innovaccer.com/?path=/docs/components-select-all--all) component.

![image](https://github.com/user-attachments/assets/cade5822-fb0c-4266-8400-5aa567c5693b)

### Motivation

We are now deprecating the [Dropdown](https://mds.innovaccer.com/?path=/docs/components-dropdown-deprecated-all--all) component and need to update all the examples with the new [Select](https://mds.innovaccer.com/?path=/docs/components-select-all--all) component.

## Steps to resolve this issue

- Fork and clone this repository
- First checkout to `develop` branch, and from that create a new branch
- Install dependencies using npm install
- Start development server using npm run dev
- Check the issue on your local environment on localhost:5000
- Refer to [this](https://github.com/innovaccer/design-system/blob/master/core/components/molecules/popover/__stories__/Layering.story.jsx)

**Comment by mostafahanafi** [comment]
i'll work on this!
