### ISSUE TITLE
Stepper: update story of Stepper component and replace Dropdown with Select component

### ISSUE THREAD

**Issue by anuradha9712** [innovaccer/design-system#2384]
## Summary

In the following stories of Stepper component, Replace the Dropdown component with the new [Select](https://mds.innovaccer.com/?path=/docs/components-select-all--all) component.

- [Stepper In Page Header](https://mds.innovaccer.com/?path=/docs/components-stepper-stepper-in-page-header--stepper-in-page-header) 

![image](https://github.com/user-attachments/assets/fdbdb3ee-a420-4f76-a7b5-c76419825e89)

- [Stepper with Animation](https://mds.innovaccer.com/?path=/docs/components-stepper-stepper-with-animation--stepper-with-animation)

![image](https://github.com/user-attachments/assets/97acb6ad-7875-4bcf-a3c4-576cda570a1e)

### Motivation

We are now deprecating the [Dropdown](https://mds.innovaccer.com/?path=/docs/components-dropdown-deprecated-all--all) component and need to update all the examples with the new [Select](https://mds.innovaccer.com/?path=/docs/components-select-all--all) component.

## Steps to resolve this issue

- Fork and clone this repository
- First checkout to `develop` branch, and from that create a new branch
- Install dependencies using npm install
- Start development server using npm run dev
- Check the issue on your local environment on localhost:5000
- Refer to [Stepper In Page Header](https://github.com/innovaccer/design-system/blob/master/core/components/molecules/stepper/__stories__/StepperInPageHeader.story.jsx)  & [Stepper with Animation](https://github.com/innovaccer/design-system/blob/master/core/components/molecules/stepper/__stories__/StepperWithAnimation.story.jsx)

**Comment by mostafahanafi** [comment]
working on it :)
