### ISSUE TITLE
Tabs: update story of Tabs component and replace Dropdown with Select component 

### ISSUE THREAD

**Issue by anuradha9712** [innovaccer/design-system#2386]
## Summary

In Tabs component, Replace the Dropdown component with the new [Select](https://mds.innovaccer.com/?path=/docs/components-select-all--all) component in the following stories:

- [Basic Tabs](https://mds.innovaccer.com/?path=/docs/components-tabs-basic-tabs--basic-tabs)
- [Inline Content](https://mds.innovaccer.com/?path=/docs/components-tabs-inline-content--inline-content)
- [Tabs With Count](https://mds.innovaccer.com/?path=/docs/components-tabs-tabs-with-count--tabs-with-count)

### Motivation

We are now deprecating the [Dropdown](https://mds.innovaccer.com/?path=/docs/components-dropdown-deprecated-all--all) component and need to update all the examples with the new [Select](https://mds.innovaccer.com/?path=/docs/components-select-all--all) component.

## Steps to resolve this issue

- Fork and clone this repository
- First checkout to `develop` branch, and from that create a new branch
- Install dependencies using npm install
- Start development server using npm run dev
- Check the issue on your local environment on localhost:5000
- Refer to [this](https://github.com/innovaccer/design-system/blob/master/core/components/molecules/tabs/__stories__/BasicTabs.story.jsx)

**Comment by mostafahanafi** [comment]
i'd like to tackle this issue

**Comment by mostafahanafi** [comment]
@anuradha9712 done! i've also done similar PRs for different sections over the past few days #2392 and #2395 if you'd like to look over them :)
