### ISSUE TITLE
HorizontalNav: update story of HorizontalNav component and replace Dropdown with Select component

### ISSUE THREAD

**Issue by anuradha9712** [innovaccer/design-system#2387]
## Summary

In [Horizontal Nav](https://mds.innovaccer.com/?path=/docs/components-horizontalnav-left-aligned--left-aligned) story, Replace the Dropdown component with the new [Select](https://mds.innovaccer.com/?path=/docs/components-select-all--all) component.

![image](https://github.com/user-attachments/assets/5e6c6d52-48c4-4f66-930b-da42a6d142ac)

### Motivation

We are now deprecating the [Dropdown](https://mds.innovaccer.com/?path=/docs/components-dropdown-deprecated-all--all) component and need to update all the examples with the new [Select](https://mds.innovaccer.com/?path=/docs/components-select-all--all) component.

## Steps to resolve this issue

- Fork and clone this repository
- First checkout to develop branch, and from that create a new branch
- Install dependencies using npm install
- Start development server using npm run dev
- Check the issue on your local environment on localhost:5000
- Refer to [this](https://github.com/innovaccer/design-system/blob/master/core/components/organisms/horizontalNav/__stories__/leftAlign.story.jsx)

**Comment by Snehalgupta-07** [comment]
Hi @anuradha9712 i can do this task can u pls assign it to me :)

**Comment by anuradha9712** [comment]
@Snehalgupta-07 Any update on this?

**Comment by youngheart12** [comment]
@anuradha9712 please assign this to me

**Comment by youngheart12** [comment]
@anuradha9712 Please review
