### ISSUE TITLE
PageHeader: update stories of PageHeader component and replace Dropdown with Select component

### ISSUE THREAD

**Issue by anuradha9712** [innovaccer/design-system#2389]
## Summary

In the following stories of Pageheader, replace the Dropdown component with the new [Select](https://mds.innovaccer.com/?path=/docs/components-select-all--all) component.

- [Responsiveness](https://mds.innovaccer.com/?path=/docs/components-pageheader-responsiveness--responsiveness)
- [Level 1/With back button/With Navigation](https://mds.innovaccer.com/?path=/docs/components-pageheader-level-1-with-back-button-with-navigation--with-navigation)
- [Level 1/With back button/With Stepper](https://mds.innovaccer.com/?path=/docs/components-pageheader-level-1-with-back-button-with-stepper--with-stepper)
- [Level 1/With back button/With Tabs](https://mds.innovaccer.com/?path=/docs/components-pageheader-level-1-with-back-button-with-tabs--with-tabs)
- [Level 1/With breadcrumb/With Stepper](https://mds.innovaccer.com/?path=/docs/components-pageheader-level-1-with-breadcrumb-with-stepper--with-stepper)

### Motivation

We are now deprecating the [Dropdown](https://mds.innovaccer.com/?path=/docs/components-dropdown-deprecated-all--all) component and need to update all the examples with the new [Select](https://mds.innovaccer.com/?path=/docs/components-select-all--all) component.

## Steps to resolve this issue

- Fork and clone this repository
- First checkout to develop branch, and from that create a new branch
- Install dependencies using npm install
- Start development server using npm run dev
- Check the issue on your local environment on localhost:5000
- Refer to [this](https://github.com/innovaccer/design-system/blob/master/core/components/organisms/pageHeader/__stories__/Responsiveness.story.jsx)

**Comment by Radha2786** [comment]
i would like to tackle this issue. Can you please assign this to me

**Comment by anuradha9712** [comment]
@Radha2786 Any update on this?

**Comment by youngheart12** [comment]
@anuradha9712 Please assign this to me
