### ISSUE TITLE
Dropdown: maxWidth prop doesn't apply below 128

### ISSUE THREAD

**Issue by Harshit369** [innovaccer/design-system#239]
## Description

maxWidth prop in Dropdown doesn't apply on the button when passed with any number below 128. This probably happens because of the min-width rule that restricts it to 128px

![image](https://user-images.githubusercontent.com/7912702/88039834-b5c5dc80-cb65-11ea-8815-1ce5db19dae8.png)

**Comment by aditya-kumawat** [comment]
As per the design guidelines, dropdown should have a min-width: 128px. Will discuss this with design-team.
