### ISSUE TITLE
Table: update story of Table component and replace Dropdown with Menu component

### ISSUE THREAD

**Issue by anuradha9712** [innovaccer/design-system#2390]
## Summary

In [Table](https://mds.innovaccer.com/?path=/docs/components-table-resource-table--resource-table) story, Replace the Dropdown component with the new [Menu](https://mds.innovaccer.com/?path=/docs/components-menu-all--all) component.

![image](https://github.com/user-attachments/assets/07530a21-bc6b-49ef-80fe-0d715ca89484)

### Motivation

We are now deprecating the [Dropdown](https://mds.innovaccer.com/?path=/docs/components-dropdown-deprecated-all--all) component and need to update all the examples with the new [Menu](https://mds.innovaccer.com/?path=/docs/components-menu-all--all) component.

## Steps to resolve this issue

- Fork and clone this repository
- First checkout to `develop` branch, and from that create a new branch
- Install dependencies using `npm install`
- Start development server using `npm run dev`
- Check the issue on your local environment on localhost:5000
- Refer to [this](https://github.com/innovaccer/design-system/blob/master/core/components/organisms/table/__stories__/ResourceTable.story.jsx)

**Comment by paradoxxx09** [comment]
I'd like to take responsibility of this issue and replace the Dropdown component with the new Menu component in the table story. Could you please assign it to me?

Thanks!

**Comment by anuradha9712** [comment]
@paradoxxx09 Any update on this?

**Comment by youngheart12** [comment]
@anuradha9712 please assign this to me

**Comment by youngheart12** [comment]
@anuradha9712 Please review
