### ISSUE TITLE
Table: align property in column schema doesn't reflect on UI

### ISSUE THREAD

**Issue by Harshit369** [innovaccer/design-system#263]
## Description

passing `align: "right"` to schema column doesn't have any impact on what renders..

**Comment by aditya-kumawat** [comment]
It wasn't working on few of the `cellType`, I already fixed it in one of the pending PR: #248.
Can you specifically mention which `cellType` were you using?

**Comment by Harshit369** [comment]
@aditya-kumawat for me it's not working for 'DEFAULT', as I'm not passing any `cellType` in the schema. 
for context:  I'm using `v1.1.0-1`

**Comment by aditya-kumawat** [comment]
@Harshit369 Will test it out and fix it(if needed).
