### ISSUE TITLE
Table: add prop to configure horizontal and vertical borders 💡

### ISSUE THREAD

**Issue by Harshit369** [innovaccer/design-system#264]
## Summary

Brief explanation of the feature.

As per the current docs, there's no config to draw vertical grid lines(border) in the table. The table by default comes with horizontal lines for each row and that too is non-configurable as of now. all I'm asking is to allow both horizontal and verticals grid lines with the option to configure from outside.

### Basic example

Our design has both kinds of table:

**with**
![image](https://user-images.githubusercontent.com/7912702/89287138-06aef800-d671-11ea-8ecf-65dc6c4cb1d6.png)

**without**
![image](https://user-images.githubusercontent.com/7912702/89287198-1f1f1280-d671-11ea-9f02-068e19c9a827.png)

**Comment by aditya-kumawat** [comment]
Horizontal separator are not configurable as per the design-guidelines.
Vertical separators are already configurable and can be enable by passing `separator: true` for specific column in Schema.
`separator: true` shows left-border for the column.

**Comment by Harshit369** [comment]
Is there any specific reason/requirement that we have them at column level and not a Grid level props?

**Comment by varundhawan5792** [comment]
@Harshit369 The property can be set for the table using `separator: true` but it's customizable for a column as well.
