### ISSUE TITLE
Table: mutates the original object passed as data prop

### ISSUE THREAD

**Issue by Harshit369** [innovaccer/design-system#265]
## Description

The original object passed as data to the table evolves with the internal table operations
Should work in an immutable way instead

**Comment by aditya-kumawat** [comment]
Not able to reproduce this issue. Can you please attach the code snippet?

**Comment by satyamyadav** [comment]
@Harshit369  Can you please help @aditya-kumawat  reproduce the issue.

**Comment by Harshit369** [comment]
@aditya-kumawat please refer this working sandbox [here](https://codesandbox.io/s/inspiring-maxwell-7bve1?file=/src/App.js) to replicate this.
