### ISSUE TITLE
DatePicker issues

### ISSUE THREAD

**Issue by amitb01** [innovaccer/design-system#268]
Unintended behavior:
1. Getting typescript error on setting **_icon_** and **_placeholder_** in _inputOptions_. Also **_mask_** is a compulsory prop but in my case I don't want to use it. 
```
<DatePicker            
   inputOptions={{ icon: 'event', placeholder: 'MM/DD/YYYY' }}
/>
```

Feature requests:
1. The Datepicker is huge right now and its looking very bad. Give the option to set its size (like small/medium/large). 
2. Like Select control type, give option to **_closeOnSelect_**

**Comment by aditya-kumawat** [comment]
DatePicker withInput is supposed to work with InputMask. If you don't want to use it, you can use your own Popover with DatePicker(withInput: false) to handle it .

Feature requests:
1. Not required as per the designer as of now.
2. @riyalohia will look into in by end of this week.
