### ISSUE TITLE
Table: General fixes

### ISSUE THREAD

**Issue by aditya-kumawat** [innovaccer/design-system#312]
## Description

- [ ] GridCell overflow: 'hidden' not required. 
- [ ] Extra space before/after Table Body Rows(need to reproduce).
- [ ] Table: support for default page number, totalRecords(not sure yet).
- [ ] Table: update default minWidth of GridCell.

### Steps to reproduce

Clear steps describing how to reproduce the issue.

### Expected result

What should happen?

### Actual result

What happened.

**Comment by ypahalajani** [comment]
@aditya-kumawat @satyamyadav 

Also, when I am using external pagination by setting `withPagination` prop to `false`, I get type error that the prop `paginationType` is a mandatory prop.

I am not sure whether TS has support to make certain props mandatory based on other prop's value.
But, just in case, this support is not there is TS, I think we can make this prop (`paginationType`) optional and set the default value as 'basic' or whatever the team decides.

What do you guys think?

P.S. I am using `@innovaccer/design-system: 1.1.0-7`
