### ISSUE TITLE
Table: onRowClick doesn't respond to clicks

### ISSUE THREAD

**Issue by Harshit369** [innovaccer/design-system#326]
## Description

OnRowClick callback prop doesn't respond to user click action 

"@innovaccer/design-system": "1.1.0-8",

**Comment by aditya-kumawat** [comment]
@Harshit369 `onRowClick` works if Table type is "resource". Are you facing issue even if you are using correct Table type?

**Comment by Harshit369** [comment]
Ok. I was not aware of this. Does adding `type='resource'` have any other impact on the table? What are we achieving with `type` prop? as I found no specific detail in the docs in front of this prop.

**Comment by aditya-kumawat** [comment]
Detailed documentation and usage guideline for every component can be found on design system documentation site(zeroheight). For Table `type`, please refer this link: https://design.innovaccer.com/0ee0e5c39/p/77fb5b-table/t/209428
