### ISSUE TITLE
Pre select all selected values in options not working

### ISSUE THREAD

**Issue by im-vikram** [innovaccer/design-system#38]
## Description

When Dropdown is passed a list in options. When then item in list having selected true/false should be respectively checked/unchecked(pre-selected). Which is not working

### Steps to reproduce

1.Populate list with options as a list which some pre selected or pre selected 
2. Open dropdown.
3. Selected values for not checked/unchecked

### Expected result

Values show be checked appropriately

### Actual result

Values were not checked at all.

**Comment by aditya-kumawat** [comment]
It has been temporarily removed from the dropdown due to some design constraint. Will be added again in the next release.

**Comment by satyamyadav** [comment]
This is added as feature with prop `selected` and type `interface Selected {
  label: string[];
  value: any[];
}
` 
[Story Link](https://innovaccer.github.io/design-system/?path=/story/atoms-dropdown-variants--pre-selection)
Release: [v1.0.0-9](https://github.com/innovaccer/design-system/releases/tag/v1.0.0-9)
