### ISSUE TITLE
Table draggable is set to false and still be able to reorder the columns

### ISSUE THREAD

**Issue by supreethr** [innovaccer/design-system#423]
Attaching the gif here for reference : 
https://innovaccer.github.io/design-system/?path=/docs/organisms-table--sync-table

![captured (3)](https://user-images.githubusercontent.com/37368321/96693924-6e89fa80-13a5-11eb-8fa1-02af5ca28414.gif)

**Comment by aditya-kumawat** [comment]
I request you to add more information while raising a bug issue. Atleast add Steps to reproduce.
Issue here is: 
If we select text on GridHead Cell and drag it, it reorders column even when `draggable: false`.
