### ISSUE TITLE
PageHeader Navigation is misaligned after update to new version of design system

### ISSUE THREAD

**Issue by supreethr** [innovaccer/design-system#424]
## Description

Page Header Navigation is misaligned from the center and attached image for reference.
<img width="1440" alt="Screenshot 2020-10-21 at 1 28 44 PM" src="https://user-images.githubusercontent.com/37368321/96694808-8910a380-13a6-11eb-8ebc-60ee16c2fcf4.png">

### Steps to reproduce

Update to new design system version

### Expected result

Navigation should be at the center of the page header
### Actual result

Navigation section has aligned towards left

**Comment by aditya-kumawat** [comment]
@supreethr Can you please mention steps to reproduce the issue on storybook?
