### ISSUE TITLE
Typo in contribution guideline heading

### ISSUE THREAD

**Issue by g3kgirl** [innovaccer/design-system#430]
## Summary
There is a typing error in contribution guideline heading "Colding guidelines for a component" at https://github.com/innovaccer/design-system/blob/master/CONTRIBUTING.md#colding-guidelines-for-a-component where "Colding" should be "Coding".

**Comment by MSTEWARDSON** [comment]
Mind if I fix this issue?

**Comment by Sumit2399** [comment]
hey @g3kgirl ,can I fix the issue?

**Comment by pragapraga** [comment]
Can I work on this? @g3kgirl
