### ISSUE TITLE
Z - Index as a prop for Modal

### ISSUE THREAD

**Issue by anmolmalik97** [innovaccer/design-system#470]
## Summary

I believe exposing a simple z-index prop for the modal would be great.

### Basic example

<Modal zIndex={1000}/>

### Motivation

There are few places where we don't have control over zIndex of other popovers. Hence requesting to include this as a simple prop. So, we can make sure modal is coming up correctly.

**Comment by riyalohia** [comment]
@anmolmalik97 Can you please mention the use case in which the modal is not appearing at the desired layer?
