### ISSUE TITLE
Support for react element as a label in Navigation Tab

### ISSUE THREAD

**Issue by anmolmalik97new** [innovaccer/design-system#484]
## Summary

As of now, the Navigation component expects label as a string. But once we pass a react element. It works but at the same time, it throws a typescript error. As the component is expecting label to be a string.

### Basic example

`` const navigationOptions = [
      {
        name: 'todos',
        label: (
          <TabLabel
            label="To-do's"
            count={todoCount}
            active={tab === 'todos'}
          />
        ),
        link: `/test`,
      }
] ``

### Motivation

To make it more generic

**Comment by aditya-kumawat** [comment]
This won't be allowed as per design guidelines. Support for count in Navigation will be added soon.

**Comment by satyamyadav** [comment]
This is resolved by #592 , so closing it.
