### ISSUE TITLE
Dropdown: value prop type

### ISSUE THREAD

**Issue by mukuljainx** [innovaccer/design-system#580]
**Question:**
Is there any prop in option where I can pass some sort of metadata like an object or array? related to that object so I don't have to loop over again the options array to retrieve those values.

**Suggestion:**
Right now we have [`value`  field in `optionSchema` which is of `any`](https://github.com/innovaccer/design-system/blob/master/core/components/atoms/dropdown/Dropdown.tsx#L59) type which can lead to errors if someone instead of `string | number` provided an object which might be intentional or by mistake, this [equality](https://github.com/innovaccer/design-system/blob/master/core/components/atoms/dropdown/Dropdown.tsx#L347) will always **falsy**  in that case. While it will be very rare as most of us can predict the equality condition using value, but why leave scope for the bug.

**Comment by satyamyadav** [comment]
@mukuljainx  Thanks for getting our attention at it, we will be looking into this issue proactively and try to resolve it as soon as possible.
