### ISSUE TITLE
Dropdown option is disable but click event fired

### ISSUE THREAD

**Issue by atifzaidi** [innovaccer/design-system#666]
## Description

- use a Table
- use onRowClick function
- use a dropdown component inside a cell with some option with disabled true
- Click on the disabled dropdown value
- onRowClick is called

### Steps to reproduce

- use a Table
- use onRowClick function
- use a dropdown component inside a cell with some option with disabled true
- Click on the disabled dropdown value
- onRowClick is called
- use [code](https://codesandbox.io/s/epic-beaver-ytd6r?file=/index.js) for demo

### Expected result

dropdown click should the event.

IMO, just move [stopPropagation](https://github.com/innovaccer/design-system/blob/ea9e455286cca645122f770a90f3e7c5801f658a/core/components/atoms/dropdown/option/index.tsx#L128) before return.

### Actual result

the click event is passed to the parent component.

**Comment by riyalohia** [comment]
@atifzaidi Thanks for pointing out the issue, we will try to resolve it as soon as possible.
