### ISSUE TITLE
Extra space between Breadcrumb and Status hint inside PageHeader component.

### ISSUE THREAD

**Issue by aman97kalra** [innovaccer/design-system#775]
## Description

Extra space between Breadcrumb and Status hint inside PageHeader component
https://codesandbox.io/s/suspicious-bird-tvrrs?file=/index.js

## Clear steps describing how to reproduce the issue.

Login on engine staging. Open Patients tab, select any patient and click on any ticket. Observe the extra space between breadcrumb and status hint at the top of the ticket

### Expected result

No extra space should be present.

### Actual result

Extra space is there.

**Comment by satyamyadav** [comment]
In PageHeader component the `Title` prop is required.
