### ISSUE TITLE
FileUpload component should also have file drag and drop functionality

### ISSUE THREAD

**Issue by atifzaidi92** [innovaccer/design-system#791]
Need a file upload component with drag and drop functionality.
Right now, we are using [react drop zone](https://www.npmjs.com/package/react-dropzone) component for that.

**Comment by riyalohia** [comment]
We have Dropzone component for that. Please refer: [https://innovaccer.github.io/design-system/?path=/docs/components-dropzone-variants-dropzone-with-filelist--dropzone-with-filelist](https://innovaccer.github.io/design-system/?path=/docs/components-dropzone-variants-dropzone-with-filelist--dropzone-with-filelist)
