### ISSUE TITLE
Input is showing icon with no text

### ISSUE THREAD

**Issue by atifzaidi92** [innovaccer/design-system#792]
## Description

If there is no value and input is disabled, UI is showing an icon on the right side
### Steps to reproduce

```
      <Input actionIcon={<Icon name="visibility_off" />}
      name="input"
      onChange={function(_){}}
      placeholder="Placeholder"
      type="text"
      disabled
      value=""
      />
```

### Expected result
no icon in this case on the right side

### Actual result
able to see the right side icon in case. empty input value

**Comment by satyamyadav** [comment]
@atifzaidi92  Thank you for bringing this to our attention; we will work to resolve it as quickly as possible.
