### ISSUE TITLE
DatePicker | Clicking on next and previous buttons submits the form when the component is rendered inside a form

### ISSUE THREAD

**Issue by ypahalajani** [innovaccer/design-system#796]
## Description

When using the DatePicker component inside a form, on click the next and previous month buttons, the form is being submitted.

### Steps to reproduce

Browser: Edge/Chrome

1. Render the DatePicker inside a form
2. Click on the next month button in the header

### Expected result

The form should not submit.

### Actual result

The form is submitting when the intention was not to.

**Comment by riyalohia** [comment]
This issue is fixed in #797
