### ISSUE TITLE
Grid Header Issue

### ISSUE THREAD

**Issue by dhananjay-innovaccer** [innovaccer/design-system#834]
Grid columns stuck on the bottom while fetching data.

**Comment by satyamyadav** [comment]
Table seems to have collapsed as there is no height in grid body as data is blank. The table don't applies any minimus height by itself as it can be only decided while using it. The table component (I assume you are using it in sync manner ) gets height based on the props it gets, the combination of requirements are as follow: 
One of the following conditions should be fulfilled:

1. parent div has some height
2. schema + data
3. errorTemplate with some height
4. loaderSchema + loading + pageSize 
5. schema + loading + pageSize

**Comment by satyamyadav** [comment]
The issue has not sufficient information, also you can choose a template for reporting in future from here https://github.com/innovaccer/design-system/issues/new/choose
