### ISSUE TITLE
Collapsible component example (story) icon position broken for expand/collapse state toggles.

### ISSUE THREAD

**Issue by satyamyadav** [innovaccer/design-system#917]
## Summary

The icon in `Collapsible` component example (story) is shifting downward/upward on expand/collapse of the collapsible container.

Expected: 
- While hovering over the Collapsible or expanding by clicking on expand button on bottom the calendar icon should not shift its vertical position.

### Motivation

The design should be consistence in case of documentation also.

## Steps to resolve this issue

- Open the story : https://innovaccer.github.io/design-system/?path=/docs/components-collapsible-all--all
- Inspect the css of the components, add or remove some helper classes as per need.

❕ This issue is under Documentation category despite there are code changes as it does not affects underline library code or features.

**Comment by AlithAnar** [comment]
Hi, you have my sword!
