### ISSUE TITLE
HorizontalNav could not be aligned to center while using it inside PageHeader

### ISSUE THREAD

**Issue by satyamyadav** [innovaccer/design-system#920]
## Description

HorizontalNav items are not aligned to horizontal center when using in `PageHeader` component with `        navigationPosition="center"` prop.
![Screenshot 2021-10-17 at 10 55 20 AM](https://user-images.githubusercontent.com/3583587/137613248-7400c56a-adb9-4fd6-926d-c735d8130162.png)

### Steps to reproduce

- Open example (story) for the PageHeader https://innovaccer.github.io/design-system/?path=/docs/components-pageheader-level-1-with-navigation--level-1-with-navigation
- Inspect the positions of navigation items in central container of the component.

### Expected result

Navigation items should be horizontal center aligned.

### Actual result

Navigation items aligned to left of its container and hence not on the exact center of the PageHeader width.

**Comment by reginaalyssa** [comment]
Can I take this on? :)

**Comment by kits4** [comment]
I think i have solved the issue raising a PR please have look and let me know.

Thank You!!

**Comment by reginaalyssa** [comment]
Hi @kits4 @satyamyadav I have already opened a pull request to fix this. Hope you don't mind as I commented earlier that I'll be taking it on, thank you!

**Comment by kits4** [comment]
Oh i also opened  one pr actually i was working on it but didn't  comment out anything.

**Comment by satyamyadav** [comment]
@reginaalyssa @kits4  Can you please review both of your PRs and see if we align to the changes, also your PRs need to be on develop branch. 
I will add some mote issues as soon as possible, to work on.

**Comment by reginaalyssa** [comment]
Hi @satyamyadav I've updated the pull request to have `develop` as its destination branch. With regards to the changes, it seems that both solutions (from myself and @kits4) seem to have fixed the issue reported here, just in different ways. Hoping to ask for your opinion on which one to go for, as they are alternate solutions to the same problem.
